### ISSUE TITLE
Create a Knative channel provisioner for Kinesis

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/aws-kinesis-channel#1]
upstream has 3 provisioners:

https://github.com/knative/eventing/tree/master/contrib

gcppusbub, nats and kafka.

We did an MQ one .

This overall issue is about creating a knative channel provisioner using Kinesis.

Basically:

- Create a Knative Channel of type Kinesis should create a Kinesis topic.
- Messages received on the kinesis topic should be fanout to all subcribers.

very similar to GCP pubsub.

**Comment by tzununbekov** [comment]
@danieltahara Hi, I don't think that we have updated docs with the latest Eventing Broker specs, but here how they should look like:

1. create k8s Secret with AWS keys to let Broker access Kinesis service:
```
apiVersion: v1
kind: Secret
metadata:
  name: awscreds
data:
  aws_access_key_id: <access key>
  aws_secret_access_key: <secret key>
```

2. create Configmap with channelTemplateSpec with AWS region and secret name created before:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-br-kinesis-channel
data:
  channelTemplateSpec: |
    apiVersion: messaging.triggermesh.dev/v1alpha1
    kind: KinesisChannel
    metadata:
      annotations:
        messaging.knative.dev/subscribable: v1beta1
    spec:
      account_region: <region, eg. us-east-2>
      account_creds: <secret name, eg. awscreds>
```

3. create Broker from the Configmap template:
```
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: MTChannelBasedBroker
  name: kinesis-default
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: config-br-kinesis-channel
```
You can have as many AWS cred secrets as you want and run Brokers backed by different Kinesis services. 

Please do not hesitate to create new issues if something is not clear or doesn't work - we're thankful for any feedback.
