### ISSUE TITLE
Channel not reporting to Broker on failure.

### ISSUE THREAD

**Issue by odacremolbap** [triggermesh/aws-kinesis-channel#46]
I'm hitting a case where a Broker that references a Kinesis configmap misformated is reporting ready.

Steps to reproduce:

Create configmap that has been added the `MISTAKE` word in it at the credentials field.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-test-kinesis-channel-json
data:
  channelTemplateSpec: '{"apiVersion":"messaging.triggermesh.dev/v1alpha1","kind":"KinesisChannel","metadata":{"annotations":{"messaging.knative.dev/subscribable":"v1beta1"}},"spec":{"account_region":"us-east-1","account_credsMISTAKE":"awscreds"}}'
```

Create broker  pointing to the configuration above

```yaml
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: broker-json
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: config-test-kinesis-channel-json
```

Broker reports ready but the channel is not
```sh
kubectl get broker -n sebgoa
NAME          URL                                                                           AGE   READY   REASON
broker-json   http://broker-ingress.knative-eventing.svc.cluster.local/sebgoa/broker-json   12s   True    

kubectl get kinesischannels.messaging.triggermesh.dev -n sebgoa                               
NAME                      READY     REASON   HOSTNAME                                                      AGE
broker-json-kne-trigger   Unknown            broker-json-kne-trigger-kn-channel.sebgoa.svc.cluster.local   90s
```
